server {
    listen 80;
    server_name ops.hamyar.app;

    # certbot webroot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 200 'waiting for ssl';
        add_header Content-Type text/plain;
    }
}
