module.exports = {
  apps: [
    {
      name: 'hamyar-ops-api',
      cwd: '/opt/hamyar/ops/api',
      script: 'dist/main.js',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      env: {
        NODE_ENV: 'production',
        PORT: '3005',
      },
      env_file: '.env',
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/hamyar/ops-api-error.log',
      out_file: '/var/log/hamyar/ops-api-out.log',
      merge_logs: true,
      kill_timeout: 10000,
      listen_timeout: 8000,
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: 'hamyar-ops-ui',
      cwd: '/opt/hamyar/ops/web/apps/web',
      script: 'server.js',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      env: {
        NODE_ENV: 'production',
        PORT: '3004',
        HOSTNAME: '0.0.0.0',
      },
      env_file: '.env',
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/hamyar/ops-ui-error.log',
      out_file: '/var/log/hamyar/ops-ui-out.log',
      merge_logs: true,
      kill_timeout: 10000,
      listen_timeout: 8000,
      restart_delay: 3000,
      max_restarts: 10,
    },
  ],
};
