import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../../infrastructure/prisma/prisma.service';
import { NginxService } from '../nginx/nginx.service';
import { CreateMicroserviceProjectDto, CreateMicroserviceDto, UpdateMicroserviceDto, LoadBalancerStatusDto } from '@hamyar-ops/shared';

@Injectable()
export class MicroservicesService {
  constructor(
    private prisma: PrismaService,
    private nginxService: NginxService,
  ) {}

  async findAllProjects() {
    return this.prisma.microserviceProject.findMany({
      include: {
        services: true,
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  async findProjectById(id: string) {
    const project = await this.prisma.microserviceProject.findUnique({
      where: { id },
      include: { services: true },
    });
    if (!project) throw new NotFoundException('Project not found');
    return project;
  }

  async createProject(dto: CreateMicroserviceProjectDto) {
    return this.prisma.microserviceProject.create({
      data: {
        name: dto.name,
        domain: dto.domain,
        description: dto.description,
      },
    });
  }

  async deleteProject(id: string) {
    return this.prisma.microserviceProject.delete({
      where: { id },
    });
  }

  async addService(dto: CreateMicroserviceDto) {
    return this.prisma.microservice.create({
      data: {
        projectId: dto.projectId,
        name: dto.name,
        pm2Prefix: dto.pm2Prefix,
        deployPath: dto.deployPath,
        startCmd: dto.startCmd,
        basePort: dto.basePort,
        targetInstances: dto.targetInstances ?? 1,
        healthUrl: dto.healthUrl,
        routePrefix: dto.routePrefix,
      },
    });
  }

  async updateService(id: string, dto: UpdateMicroserviceDto) {
    return this.prisma.microservice.update({
      where: { id },
      data: { ...dto },
    });
  }

  async removeService(id: string) {
    return this.prisma.microservice.delete({
      where: { id },
    });
  }

  async generateNginxConfig(projectId: string) {
    const project = await this.findProjectById(projectId);
    if (!project.domain) throw new BadRequestException('Project requires a domain to generate Nginx config');
    
    let config = `# Auto-generated by Hamyar Ops for Microservice Project: ${project.name}\n\n`;

    // Generate upstreams
    for (const svc of project.services) {
      config += `upstream ${svc.pm2Prefix}_upstream {\n`;
      for (let i = 0; i < svc.targetInstances; i++) {
        config += `    server 127.0.0.1:${svc.basePort + i};\n`;
      }
      config += `}\n\n`;
    }

    // Generate server block
    config += `server {\n`;
    config += `    listen 80;\n`;
    config += `    server_name ${project.domain};\n\n`;

    for (const svc of project.services) {
      if (svc.routePrefix) {
        config += `    location ${svc.routePrefix} {\n`;
        config += `        proxy_pass http://${svc.pm2Prefix}_upstream;\n`;
        config += `        proxy_set_header Host $host;\n`;
        config += `        proxy_set_header X-Real-IP $remote_addr;\n`;
        config += `    }\n`;
      }
    }

    config += `}\n`;
    return { config, projectName: project.name };
  }

  async getNginxStatus(projectId: string): Promise<LoadBalancerStatusDto> {
    const generated = await this.generateNginxConfig(projectId);
    const confName = `${generated.projectName.toLowerCase().replace(/[^a-z0-9-]/g, '')}-lb.conf`;
    
    let isApplied = false;
    let isEnabled = false;
    
    try {
      const existing = await this.nginxService.getConfig(confName);
      // It's applied if the content matches
      isApplied = existing.content.trim() === generated.config.trim();
      isEnabled = existing.enabled;
    } catch {
      // File doesn't exist
    }

    // Pre-validate
    const validation = await this.nginxService.validateContent(generated.config);

    return {
      config: generated.config,
      isApplied,
      isEnabled,
      isValid: validation.valid,
      validationOutput: validation.output,
    };
  }

  async applyNginxConfig(projectId: string) {
    const status = await this.getNginxStatus(projectId);
    if (!status.isValid) {
      throw new BadRequestException(`Generated configuration is invalid: ${status.validationOutput}`);
    }

    const project = await this.findProjectById(projectId);
    const confName = `${project.name.toLowerCase().replace(/[^a-z0-9-]/g, '')}-lb.conf`;

    // Write config and enable
    await this.nginxService.updateConfig(confName, status.config);
    await this.nginxService.enableSite(confName);
    
    // Safely reload
    const reloadResult = await this.nginxService.reload();
    return { success: true, message: reloadResult.output };
  }

  async disableNginxConfig(projectId: string) {
    const project = await this.findProjectById(projectId);
    const confName = `${project.name.toLowerCase().replace(/[^a-z0-9-]/g, '')}-lb.conf`;

    try {
      await this.nginxService.disableSite(confName);
      const reloadResult = await this.nginxService.reload();
      return { success: true, message: reloadResult.output };
    } catch (e: any) {
      throw new BadRequestException(`Failed to disable site: ${e.message}`);
    }
  }
}
